name: Deploy static cntent to Pages
on:
  push:
    branches: ["main"]

jobs:
  build-docs:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install sphinx sphinx_rtd_theme sphinx-tabs sphinx_toolbox
      - name: Sphinx build
        run: |
          sphinx-apidoc -o docs NiChart_DLMUSE/
          cd docs/
          make html
          cd ..

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3

        with:
          path: docs/_build/html
          retention-days: 90

  deploy-docs:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: build-docs

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.output.page_url }}

    concurrency:
      group: "pages"
      cancel-in-progress: true

    runs-on: ubuntu-latest
    steps:
      - name: Deploy artifact to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
