import React from 'react';
import Head from 'next/head';
import Header from '../components/Layout/Header';
import Footer from '../components/Layout/Footer';
import Favicons from '../components/Favicons/Favicons';
import styles from '../styles/Quickstart.module.css';
import { Grid, Paper, Box, Typography, Accordion, AccordionSummary, AccordionDetails } from '@mui/material';
import { Heading, Divider, Link } from '@aws-amplify/ui-react';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';

const Quickstart = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NiChart | Quickstart</title>
        <Favicons />
      </Head>
      <Header />
      <div className={styles.mainContent}>
        <Paper className={styles.paper}>
          <Box textAlign="center">
            <Heading level={1}>Quickstart Guide</Heading>
            <Divider/>
          </Box>
          <Box>
            <p>If you already know you're interested in NiChart, this guide will help you get started as fast as possible.</p>
            <p>There are two ways to use NiChart: from your own machine, or via <Link href="/portal">NiChart Cloud</Link>. The easiest way to get started is to use <Link href="/portal">NiChart Cloud</Link>, accessible from this site.</p>
            <br></br>

            <Accordion>
              <AccordionSummary expandIcon={<ExpandMoreIcon />}>
                <Typography variant="h6">Registering</Typography>
              </AccordionSummary>
              <AccordionDetails>
                <p>To begin, click the "NiChart Cloud" button in the header.</p>
                <p>You will need to register an account and sign in.</p>
                <p>If you are having trouble finding the registration email, be sure to check your spam folder.</p>
              </AccordionDetails>
            </Accordion>

            <Accordion>
              <AccordionSummary expandIcon={<ExpandMoreIcon />}>
                <Typography variant="h6">Module 1: Image Processing</Typography>
              </AccordionSummary>
              <AccordionDetails>
                <p>The box on the left allows you to upload your T1 NIFTI brain scans (If you have a lot of scans, you can also upload a .zip archive.).</p>
                <p>You can drag and drop, or use the upload button.</p>
                <p>Wait for your files to upload. You can check the files currently on the backend server with the "View Uploaded Files" button.</p>
                <p>When uploading large files, you may see fluctuations in the displayed progress. Do not worry -- as long as the upload does not fail, it will correct itself.</p>
                <br></br>
                <p>When you're ready to run image processing, click "Submit Jobs". This will spin up jobs for each scan you uploaded.</p>
                <p>You'll see the jobs pop up shortly on the middle column. Wait for them to finish and show a green smiley.</p>
                <p>When they're all green, you can download your ROI volumes with "Download MUSE CSV" or download the resulting images with "Download MUSE ROIs". Be patient, it takes a second to collect your output.</p>
                <br></br>
                <p>If you like, you can export your files directly to the next module.</p>
              </AccordionDetails>
            </Accordion>
            
            <Accordion>
              <AccordionSummary expandIcon={<ExpandMoreIcon />}>
                <Typography variant="h6">Module 2: Machine Learning</Typography>
              </AccordionSummary>
              <AccordionDetails>
                <p>This module needs both your ROI volume CSV and a separate demographics CSV file.</p>
                <p>Press "Download Template" to see an example of the demographics CSV.</p>                
                <p>Use the file uploaders on the left to upload both files.</p>
                <p>The rows in the demographic CSV should correspond with the same filenames from Module 1.</p>
                <p>You can select which models to run on your data with the "Select Models" button.</p>
                <p>When you're ready, hit "Generate SPARE Scores". One job will appear in the job list to the right.</p>
                <p>Wait for the job to complete, then you can download your full results with "Download SPARE score CSV". This file will have not only your ROI volumes, but also your demographic information and the SPARE scores generated by the models you selected.</p>
                <p>You can then export your data to Module 3 where you can visualize it.</p>
              </AccordionDetails>
            </Accordion>

            <Accordion>
              <AccordionSummary expandIcon={<ExpandMoreIcon />}>
                <Typography variant="h6">Module 3: Visualization</Typography>
              </AccordionSummary>
              <AccordionDetails>
                <p>This module allows you to view age trends of selected Regions of Interest in your data together with centile curves that were derived from NiChart reference samples.</p>
                <p>Either upload your CSV from Module 2, or upload your own file. Be aware that if you upload your own file, it may not have all the fields needed to perform charting against reference datasets.</p>
                <p>Select the ROI you want to know about and click "Add Plot". This will show you how the scans you uploaded compare to the trends for the reference data.</p>
                <p>At any time, you can change the reference dataset to view your scans in comparison to a different reference set.</p>
              </AccordionDetails>
            </Accordion>

            <Accordion>
              <AccordionSummary expandIcon={<ExpandMoreIcon />}>
                <Typography variant="h6">Running the pipelines locally</Typography>
              </AccordionSummary>
              <AccordionDetails>
                <p><b>Image Processing:</b></p>
                <p>You can access the image processing pipeline we utilize in the <a href="https://github.com/CBICA/NiChart_DLMUSE">NiChart_DLMUSE</a> package. This pipeline is built on the <a href="https://github.com/MIC-DKFZ/nnUNet/tree/nnunetv1">nnUNet</a> framework, and detailed instructions are available in the repository's <a href="https://github.com/CBICA/NiChart_DLMUSE/blob/main/README.md">Readme</a>. Models for all pipelines are located in the <a href="https://github.com/CBICA/NiChart_DLMUSE/releases">Releases</a> section as release <a href="https://github.com/CBICA/NiChart_DLMUSE/releases/tag/0.1.7">assets</a>. All pipelines are accompanied with a docker container, which you can easily download and run without any installation procedure. More information can be found in the repositories' installation and usage instructions.</p>
                <p>More pipelines are scheduled to be integrated in the NiChart Cloud, and of course made available through public repositories for local execution.</p>
                <br></br>
                <p><b>Machine Learning:</b></p>
                <p>We provide the <a href="https://github.com/CBICA/spare_score">spare_score</a> pipeline. The necessary models to operate the SPARE_scores pipeline are conveniently located in the repository's <a href="https://github.com/CBICA/spare_score/tree/main/spare_scores/mdl">/spare_scores/mdl/</a> directory. Alternatively, you can find the pipeline as a <a href="https://hub.docker.com/repository/docker/aidinisg/spare_scores/general">docker container</a> (models included).</p>
                <p>Machine learning pipelines are models are constantly under development and will be integrated to the NiChart Cloud as soon as possible and we will be providing public repositories for local execution.</p>
                <br></br>
                <p><b>Visualization:</b></p>
                <p>While we recommend visualizing the results of your pipeline through the NiChart Cloud, we are commited to providing alternatives for local execution and visualization. To that end, we have an open-source, PyQT-based alternative called <a href="https://github.com/gurayerus/NiChart_Viewer">NiChart_Viewer</a>.</p>
                <br></br>
                <p><b>Data:</b></p>
                <p>The data we've used for model training, reference centile curves, testing and validation come from the <a href="https://www.med.upenn.edu/cbica/imaging-consortia-increasing-sample-size-and-understanding-heterogeneity-in-health-and-disease.html">iSTAGING</a> project.</p>
                <p>For more information, or inquiries about the data, please contact us at <a href="mailto:nichart-devs@cbica.upenn.edu">nichart-devs@cbica.upenn.edu</a>.</p>
                <p>We will be happy to help you and answer any questions that you might have!</p>
              </AccordionDetails>
            </Accordion>

            <br></br><br></br>

            <Heading level={3}>Please visit the <a href="/faq">Frequently Asked Questions</a> if you have more questions!</Heading>
          </Box>

        </Paper>
      </div>
      <Footer />
    </div>
  );
};

export default Quickstart;
